name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
- bug
assignees:
- 4c65736975
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/VertexFloat/noMoreAutoLift/issues) before filing a new one!

- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of the modification does the problem apply to?
    options:
      - 1.0.0.7
      - 1.0.0.6
      - 1.0.0.5
      - 1.0.0.4
      - 1.0.0.3
      - 1.0.0.2
      - 1.0.0.1
      - 1.0.0.0
    default: 0
  validations:
    required: true

- type: dropdown
  id: game
  attributes:
    label: Game Version
    description: Check the top left corner of the game's main menu.
    options:
      - Farming Simulator 25 (1.2.1.0)
    default: 0
  validations:
    required: true

- type: textarea
  attributes:
    label: 👣 Steps to reproduce
    description: I strongly suggest including screenshots and a bug report log ("C:\Users\USER_NAME\Documents\My Games\FarmingSimulator2025\log.txt").
    placeholder: Having detailed steps helps me reproduce the bug. 
  validations:
    required: true

- type: textarea
  attributes:
    label: ⭐️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ⛔️ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false